name: Doxygen GitHub Pages Deploy Action

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup files
        run: |
          mkdir .\docs\in
          Copy-Item -Path .\WolvenKit.Modkit\Scripting\WKitScripting.cs -Destination .\docs\in
          Copy-Item -Path .\WolvenKit.App\Helpers\WKitUIScripting.cs -Destination .\docs\in

      - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile_scripting