name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        
    - name: Publish with Dotnet
      run: dotnet publish .\WolvenKit\WolvenKit.csproj -o .\publish -c Release

    - name: create installer
      run: ISCC /O".\outinstaller" /dMyAppBaseDir="..\publish\" .\Installers\installer.iss

    - uses: actions/upload-artifact@v3
      with:
        name: installer
        path: .\outinstaller\*.exe

    ##########################################
    # Download artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: installer
        path: out

    - run: Get-ChildItem -Path./out -Recurse -Force